import type { Metadata } from "next";
import { BadgeCheck, Leaf, ShieldCheck, Users, Wrench } from "lucide-react";
import PageHero from "@/components/PageHero";
import SiteFooter from "@/components/SiteFooter";
export const metadata: Metadata = {
  title: "About VR Enterprises | Mayukh Solar",
  description: "Meet the Kota-based in-house team behind 1,000+ solar installations and 5 MW of commissioned capacity.",
  alternates: { canonical: "/about" },
  openGraph: { title: "About VR Enterprises | Mayukh Solar", description: "Meet the Kota-based in-house team behind 1,000+ solar installations and 5 MW of commissioned capacity.", url: "/about" },
};
export default function AboutPage(){return <main><PageHero eyebrow="ABOUT VR ENTERPRISES" title="Local engineering." accent="Long-term accountability." copy="A Kota-built solar company with its hands on every roof it sells, serving Rajasthan since 2020."/><section id="page-content" className="inner-section"><div className="shell about-story" data-reveal><div><div className="section-kicker">WHO WE ARE</div><h2>Solar is a 25-year asset, not a <span>one-day installation.</span></h2></div><div><p>VR Enterprises—trading as Mayukh Solar—designs, supplies and installs solar power systems across Rajasthan. What began with residential rooftops has grown into more than 1,000 installations and 5 MW of capacity, including factory sheds and a fully commissioned 1.47 MW PM KUSUM plant.</p><p>We keep the team in-house. Survey, structure, wiring, approvals and service are handled by people our customers can still reach years after commissioning.</p></div></div><div className="shell value-grid">{[[ShieldCheck,"Honest sizing","Twelve months of consumption reviewed before a system is quoted."],[Users,"In-house crew","Our own engineer and technicians install every project."],[BadgeCheck,"Paperwork included","Portal registration, subsidy, net metering and inspection supported end to end."],[Leaf,"Local service","One office, six districts and a service radius measured by a drive."],[Wrench,"Built to last","Components and protection selected for decades of generation."]].map(([Icon,title,copy])=>{const C=Icon as typeof ShieldCheck;return <article key={String(title)} data-reveal><C/><h3>{String(title)}</h3><p>{String(copy)}</p></article>})}</div></section><section className="founder-section"><div className="shell founder-grid"><div className="founder-photo" data-reveal><img src="/ashish-rathor.webp" alt="Ashish Rathor, Founder and CEO" width={820} height={1061} loading="lazy" decoding="async"/></div><div className="founder-copy" data-reveal><div className="section-kicker light">FROM THE FOUNDER</div><blockquote>“A solar plant is not a product we hand over. It is a promise we have to keep for twenty-five years.”</blockquote><p>We size every system against the customer&apos;s actual electricity bill and keep installation and service in-house. That is why our customers still call the same office.</p><div className="founder-name"><strong>Ashish Rathor</strong><span>Founder & CEO · B.Tech Electrical · M.Tech Solar · Licensed Electrical Contractor</span></div><div className="leadership"><div><strong>Mukesh Kushwaha</strong><span>Senior Sales Manager</span></div><div><strong>Ankush Rathor</strong><span>Operations & Management</span></div></div></div></div></section><SiteFooter/></main>}
