import type { Metadata } from "next";
import { CircleCheck } from "lucide-react";
import PageHero from "@/components/PageHero";
import SiteFooter from "@/components/SiteFooter";
import LeadForm from "@/components/LeadForm";
export const metadata: Metadata = {
  title: "Solar Projects | Mayukh Solar",
  description: "See commissioned rooftop, industrial and PM KUSUM solar projects delivered by VR Enterprises.",
  alternates: { canonical: "/projects" },
  openGraph: { title: "Solar Projects | Mayukh Solar", description: "See commissioned rooftop, industrial and PM KUSUM solar projects delivered by VR Enterprises.", url: "/projects" },
};
export default function ProjectsPage(){return <main><PageHero eyebrow="OUR PROJECTS" title="Five megawatts." accent="Built one site at a time." copy="A track record across home rooftops, industrial sheds and megawatt-scale ground mount."/><section id="page-content" className="inner-section"><div className="shell portfolio-grid"><article className="portfolio-feature" data-reveal><img src="/pm-kusum-plant.webp" alt="1.47 MW PM KUSUM ground-mounted solar plant" width={1450} height={637} loading="lazy" decoding="async"/><div><span>FLAGSHIP · COMMISSIONED</span><h2>1.47 MW PM KUSUM ground-mount</h2><p>Complete EPC scope from land survey, array layout and civil foundations through mounting, evacuation, metering and commissioning.</p><ul><li><CircleCheck/>1.47 MW installed capacity</li><li><CircleCheck/>Ground-mounted structure</li><li><CircleCheck/>Commissioned and exporting</li></ul></div></article><article className="portfolio-feature reverse" data-reveal><img src="/industrial-rooftop.webp" alt="Industrial tin-shed rooftop solar plant" width={1450} height={637} loading="lazy" decoding="async"/><div><span>COMMERCIAL & INDUSTRIAL</span><h2>Industrial tin-shed rooftop plant</h2><p>Elevated array installed across a profiled metal roof, retaining walkways and ventilation while engineering the structure for local wind loads.</p><ul><li><CircleCheck/>Non-penetrative mounting</li><li><CircleCheck/>Operational access retained</li><li><CircleCheck/>Complete safety protection</li></ul></div></article></div><div className="shell project-numbers expanded" data-reveal><div><strong>1000+</strong><span>Residential rooftops</span></div><div><strong>4+</strong><span>Plants above 50 kW</span></div><div><strong>5 MW</strong><span>Cumulative capacity</span></div><div><strong>6</strong><span>Districts served</span></div></div></section><section className="visit-banner"><div className="shell" data-reveal><h2>See a working system before you decide.</h2><p>We can arrange a visit to a commissioned plant of comparable size in your district.</p><a href="tel:+919782767546">Arrange a site visit →</a></div></section><section className="project-form-section"><div className="shell" data-reveal><LeadForm source="projects-cta" heading="Ask to visit a commissioned plant" copy="Leave your district and we will arrange a visit to a working system of comparable size."/></div></section><SiteFooter/></main>}
